### Edited by ADIL####
resources:
- name: app_sources_commit
  type: git
  source:
          #uri: https://github.com/concourse/concourse-docker.git
    uri: https://github.com/ArisGloba1/concourse-docker.git
    username: 
    password:
jobs:
- name: list-repo
  plan:
  - get: app_sources_commit
  - task: list-repo-content
    config:
      platform: linux
      inputs:
      - name: app_sources_commit
      image_resource:
        type: docker-image
        source: { repository: ubuntu }
      run:
        path: sh
        args:
        - -exc
        - |
          ls -R ./app_sources_commit
